export const LoginUser = "/login";
export const SignupUser = "/users";
export const GetMembershipList = "/table";
export const CreateOrder="/createOrder";
export const ExcelfileRead="/excelFileRead";
export const Alluser="/allUser";
export const ForgotPassword="/forgotPassword"
export const GetPendingList="/pending"
export const GetRejectedList="/rejectlist"
export const UpdateStatus="/status"
